
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.1/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:3 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Program Files/nodejs/"
      - "C:/Users/RUHIN/AppData/Local/Android/Sdk/platform-tools/"
      - "C:/Users/RUHIN/AppData/Local/Android/Sdk/build-tools/36.1.0/"
      - "C:/Users/RUHIN/AppData/Local/Android/Sdk/emulator/"
      - "C:/Program Files/Android/Android Studio/jbr/bin/"
      - "C:/Program Files/WireGuard/"
      - "C:/Program Files/CMake/bin/"
      - "C:/rtools42/ucrt64/bin/"
      - "C:/Users/RUHIN/Documents/MinGW64/MinGW64/"
      - "C:/Users/RUHIN/AppData/Local/Programs/Python/Python313/Scripts/"
      - "C:/Users/RUHIN/AppData/Local/Programs/Python/Python313/"
      - "C:/Users/RUHIN/AppData/Local/Programs/Python/Launcher/"
      - "C:/Users/RUHIN/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/RUHIN/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/RUHIN/AppData/Roaming/npm/"
      - "C:/rtools45/x86_64-w64-mingw32.static.posix/bin/"
      - "C:/Program Files (x86)/GnuWin32/bin/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/Program Files/Git/cmd/mingw32-make.exe.com"
      - "C:/Program Files/Git/cmd/mingw32-make.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/mingw32-make.exe.com"
      - "C:/Program Files/Docker/Docker/resources/bin/mingw32-make.exe"
      - "C:/Program Files/nodejs/mingw32-make.exe.com"
      - "C:/Program Files/nodejs/mingw32-make.exe"
      - "C:/Users/RUHIN/AppData/Local/Android/Sdk/platform-tools/mingw32-make.exe.com"
      - "C:/Users/RUHIN/AppData/Local/Android/Sdk/platform-tools/mingw32-make.exe"
      - "C:/Users/RUHIN/AppData/Local/Android/Sdk/build-tools/36.1.0/mingw32-make.exe.com"
      - "C:/Users/RUHIN/AppData/Local/Android/Sdk/build-tools/36.1.0/mingw32-make.exe"
      - "C:/Users/RUHIN/AppData/Local/Android/Sdk/emulator/mingw32-make.exe.com"
      - "C:/Users/RUHIN/AppData/Local/Android/Sdk/emulator/mingw32-make.exe"
      - "C:/Program Files/Android/Android Studio/jbr/bin/mingw32-make.exe.com"
      - "C:/Program Files/Android/Android Studio/jbr/bin/mingw32-make.exe"
      - "C:/Program Files/WireGuard/mingw32-make.exe.com"
      - "C:/Program Files/WireGuard/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "C:/rtools42/ucrt64/bin/mingw32-make.exe.com"
      - "C:/rtools42/ucrt64/bin/mingw32-make.exe"
      - "C:/Users/RUHIN/Documents/MinGW64/MinGW64/mingw32-make.exe.com"
      - "C:/Users/RUHIN/Documents/MinGW64/MinGW64/mingw32-make.exe"
      - "C:/Users/RUHIN/AppData/Local/Programs/Python/Python313/Scripts/mingw32-make.exe.com"
      - "C:/Users/RUHIN/AppData/Local/Programs/Python/Python313/Scripts/mingw32-make.exe"
      - "C:/Users/RUHIN/AppData/Local/Programs/Python/Python313/mingw32-make.exe.com"
      - "C:/Users/RUHIN/AppData/Local/Programs/Python/Python313/mingw32-make.exe"
      - "C:/Users/RUHIN/AppData/Local/Programs/Python/Launcher/mingw32-make.exe.com"
      - "C:/Users/RUHIN/AppData/Local/Programs/Python/Launcher/mingw32-make.exe"
      - "C:/Users/RUHIN/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/RUHIN/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Users/RUHIN/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "C:/Users/RUHIN/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe"
      - "C:/Users/RUHIN/AppData/Roaming/npm/mingw32-make.exe.com"
      - "C:/Users/RUHIN/AppData/Roaming/npm/mingw32-make.exe"
      - "C:/rtools45/x86_64-w64-mingw32.static.posix/bin/mingw32-make.exe.com"
      - "C:/rtools45/x86_64-w64-mingw32.static.posix/bin/mingw32-make.exe"
      - "C:/Program Files (x86)/GnuWin32/bin/mingw32-make.exe.com"
      - "C:/Program Files (x86)/GnuWin32/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Android\\Sdk\\platform-tools"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Android\\Sdk\\build-tools\\36.1.0"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Android\\Sdk\\emulator"
        - "C:\\Program Files\\Android\\Android Studio\\jbr\\bin"
        - "C:\\Program Files\\WireGuard\\"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\rtools42\\ucrt64\\bin"
        - "C:\\Users\\RUHIN\\Documents\\MinGW64\\MinGW64"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Programs\\Python\\Python313\\"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\RUHIN\\AppData\\Roaming\\npm"
        - "C:\\rtools45\\x86_64-w64-mingw32.static.posix\\bin"
        - "C:\\Program Files (x86)\\GnuWin32\\bin"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Programs\\Python\\Python313\\"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\RUHIN\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\RUHIN\\AppData\\Roaming\\npm"
...
